CREATE TABLE [dbo].[Address]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[CompanyId] INT DEFAULT NULL REFERENCES Company(Id),
	[EmployeeId] INT DEFAULT NULL REFERENCES Employee(Id),
	[Street] NVARCHAR(128) NOT NULL,
	[HouseNumber] SMALLINT NOT NULL,
	[CityId] NVARCHAR(16) NOT NULL REFERENCES City(PostCode),
	[CreationTime] DATETIME2(7) NOT NULL DEFAULT GetDate(),
	[DeleteTime] DATETIME2(7)
)
