CREATE TABLE [dbo].[City]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[PostCode] NVARCHAR(16) NOT NULL,
	[CityName] NVARCHAR(128) NOT NULL,
	[ProvinceId] INT NOT NULL REFERENCES Province(Id),
	[CreationTime] DATETIME2(7) NOT NULL DEFAULT GetDate(),
	[DeleteTime] DATETIME2(7)
)
