CREATE TABLE [dbo].[Manager]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[FirstName] NVARCHAR(128) NOT NULL,
	[LastName] NVARCHAR(128) NOT NULL,
	[CreationTime] DATETIME2(7) NOT NULL DEFAULT GetDate(),
	[DeleteTime] DATETIME2(7) NOT NULL
)
